<link href="https://fonts.googleapis.com/css?family=DM+Sans:300,400,700&amp;display=swap" rel="stylesheet">
<link rel="stylesheet" href="{{asset("assets")}}/fonts/icomoon/style.css">
<link rel="stylesheet" href="{{asset("assets")}}/css/bootstrap.min.css">
<link rel="stylesheet" href="{{asset("assets")}}/css/bootstrap-datepicker.css">
<link rel="stylesheet" href="{{asset("assets")}}/css/jquery.fancybox.min.css">
<link rel="stylesheet" href="{{asset("assets")}}/css/owl.carousel.min.css">
<link rel="stylesheet" href="{{asset("assets")}}/css/owl.theme.default.min.css">
<link rel="stylesheet" href="{{asset("assets")}}/fonts/flaticon/font/flaticon.css">
<link rel="stylesheet" href="{{asset("assets")}}/css/aos.css">
<link rel="stylesheet" href="{{asset("assets")}}/css/style.css">
